package model;

/**
 * Account - Model class representing a bank account.
 *
 * This class maps to the 'accounts' table in the database.
 * Each field here corresponds to a column in that table.
 *
 * OOP CONCEPT — ENCAPSULATION:
 * All fields are 'private'. Public getters and setters are used
 * to access and modify data in a controlled way.
 *
 * Database Table Reference:
 * ┌──────────────┬───────────────────┬──────────────────────────────────────┐
 * │ Column       │ Type              │ Notes                                │
 * ├──────────────┼───────────────────┼──────────────────────────────────────┤
 * │ account_no   │ BIGINT (PK, AI)   │ Auto-generated, starts at 1001       │
 * │ customer_id  │ INT (FK)          │ References customers(customer_id)    │
 * │ account_type │ VARCHAR(20)       │ 'SAVINGS' or 'CURRENT'               │
 * │ balance      │ DECIMAL(15,2)     │ Current balance, default 0.00        │
 * │ status       │ VARCHAR(10)       │ 'ACTIVE', 'FROZEN', or 'CLOSED'      │
 * └──────────────┴───────────────────┴──────────────────────────────────────┘
 */
public class Account {

    // --------------------------------------------------
    // Fields — all private (Encapsulation)
    // --------------------------------------------------
    private long   accountNo;    // Primary key, auto-generated by the database (BIGINT)
    private int    customerId;   // Foreign key — links this account to a customer
    private String accountType;  // 'SAVINGS' or 'CURRENT'
    private double balance;      // Current balance in the account
    private String status;       // 'ACTIVE', 'FROZEN', or 'CLOSED'

    // --------------------------------------------------
    // Constructor 1: No-argument constructor
    // --------------------------------------------------
    // Useful when you want to create an empty Account object
    // and fill values later using setters.
    public Account() {
    }

    // --------------------------------------------------
    // Constructor 2: For account creation (without accountNo)
    // --------------------------------------------------
    // When opening a new account, we don't know the accountNo yet
    // because it's auto-generated by MySQL. So this constructor takes
    // only the fields we provide — the DB handles accountNo itself.
    public Account(int customerId, String accountType, double balance, String status) {
        this.customerId  = customerId;
        this.accountType = accountType;
        this.balance     = balance;
        this.status      = status;
    }

    // --------------------------------------------------
    // Constructor 3: Full constructor (with accountNo)
    // --------------------------------------------------
    // Used when reading an account from the database, where
    // all columns including account_no are already known.
    public Account(long accountNo, int customerId, String accountType, double balance, String status) {
        this.accountNo   = accountNo;
        this.customerId  = customerId;
        this.accountType = accountType;
        this.balance     = balance;
        this.status      = status;
    }

    // --------------------------------------------------
    // Getters & Setters
    // --------------------------------------------------

    public long getAccountNo() {
        return accountNo;
    }

    public void setAccountNo(long accountNo) {
        this.accountNo = accountNo;
    }

    public int getCustomerId() {
        return customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public String getAccountType() {
        return accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    // --------------------------------------------------
    // toString() — for easy printing / debugging
    // --------------------------------------------------
    @Override
    public String toString() {
        return "Account {" +
                " accountNo=" + accountNo +
                ", customerId=" + customerId +
                ", accountType='" + accountType + '\'' +
                ", balance=" + balance +
                ", status='" + status + '\'' +
                " }";
    }
}
