package model;

/**
 * Customer - Model class representing a bank customer.
 *
 * This class maps to the 'customers' table in the database.
 * Each field here corresponds to a column in that table.
 *
 * OOP CONCEPT — ENCAPSULATION:
 * All fields are 'private', meaning no other class can access them directly.
 * Instead, we provide public getter and setter methods. This lets us control
 * how data is read and modified (e.g., we could add validation in setters later).
 *
 * Database Table Reference:
 * ┌──────────────┬───────────────┬──────────────────────────────┐
 * │ Column       │ Type          │ Notes                        │
 * ├──────────────┼───────────────┼──────────────────────────────┤
 * │ customer_id  │ INT (PK, AI)  │ Auto-generated by MySQL      │
 * │ name         │ VARCHAR(100)  │ NOT NULL                     │
 * │ email        │ VARCHAR(100)  │ NOT NULL, UNIQUE             │
 * │ phone        │ VARCHAR(15)   │ NOT NULL, UNIQUE             │
 * │ password     │ VARCHAR(255)  │ NOT NULL                     │
 * │ address      │ VARCHAR(255)  │ Optional                     │
 * │ created_at   │ TIMESTAMP     │ Auto-set by MySQL            │
 * └──────────────┴───────────────┴──────────────────────────────┘
 */
public class Customer {

    // --------------------------------------------------
    // Fields — all private (Encapsulation)
    // --------------------------------------------------
    private int customerId;     // Primary key, auto-generated by the database
    private String name;        // Customer's full name
    private String email;       // Unique email address
    private String phone;       // Unique phone number
    private String password;    // Customer's password
    private String address;     // Customer's address (optional)

    // --------------------------------------------------
    // Constructor 1: No-argument constructor
    // --------------------------------------------------
    // Useful when you want to create an empty Customer object
    // and set values later using setters.
    public Customer() {
    }

    // --------------------------------------------------
    // Constructor 2: For registration (without customerId)
    // --------------------------------------------------
    // When registering a new customer, we don't know the customerId yet
    // because it's auto-generated by MySQL. So this constructor
    // takes only the fields the user provides.
    public Customer(String name, String email, String phone, String password, String address) {
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
        this.address = address;
    }

    // --------------------------------------------------
    // Constructor 3: Full constructor (with customerId)
    // --------------------------------------------------
    // Used when reading a customer from the database, where
    // we already know the customerId.
    public Customer(int customerId, String name, String email, String phone, String password, String address) {
        this.customerId = customerId;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
        this.address = address;
    }

    // --------------------------------------------------
    // Getters & Setters
    // --------------------------------------------------
    // Each field has a 'get' method (to read) and a 'set' method (to write).
    // This is the standard Java convention for encapsulation.

    public int getCustomerId() {
        return customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    // --------------------------------------------------
    // toString() — for easy printing / debugging
    // --------------------------------------------------
    // When you do System.out.println(customer), Java calls this method.
    // We intentionally EXCLUDE the password from the output for security.
    @Override
    public String toString() {
        return "Customer {" +
                " customerId=" + customerId +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                ", address='" + address + '\'' +
                " }";
    }
}
