package model;

/**
 * Customer - Model class representing a bank customer.
 *
 * This class maps to the 'customers' table in the database.
 * Each field here corresponds to a column in that table.
 *
 * OOP CONCEPT — ENCAPSULATION:
 * All fields are 'private', meaning no other class can access them directly.
 * Instead, we provide public getter and setter methods. This lets us control
 * how data is read and modified (e.g., we could add validation in setters later).
 *
 * Database Table Reference:
 * ┌──────────────┬───────────────┬──────────────────────────────┐
 * │ Column       │ Type          │ Notes                        │
 * ├──────────────┼───────────────┼──────────────────────────────┤
 * │ customer_id  │ INT (PK, AI)  │ Auto-generated by MySQL      │
 * │ name         │ VARCHAR(100)  │ NOT NULL                     │
 * │ email        │ VARCHAR(100)  │ NOT NULL, UNIQUE             │
 * │ phone        │ VARCHAR(15)   │ NOT NULL, UNIQUE             │
 * │ password     │ VARCHAR(255)  │ NOT NULL                     │
 * │ address      │ VARCHAR(255)  │ Optional                     │
 * │ created_at   │ TIMESTAMP     │ Auto-set by MySQL            │
 * └──────────────┴───────────────┴──────────────────────────────┘
 */
public class Customer extends User {

    private String name;        // Customer's full name
    private String email;       // Unique email address
    private String phone;       // Unique phone number
    private String address;     // Customer's address (optional)

    public Customer() {
        super();
    }

    public Customer(String name, String email, String phone, String password, String address) {
        super(0, password);
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.address = address;
    }

    public Customer(int customerId, String name, String email, String phone, String password, String address) {
        super(customerId, password);
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.address = address;
    }

    public int getCustomerId() {
        return getId();
    }

    public void setCustomerId(int customerId) {
        setId(customerId);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        return "Customer {" +
                " customerId=" + getCustomerId() +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                ", address='" + address + '\'' +
                " }";
    }
}
