package model;

/**
 * Transaction - Model class representing a bank transaction.
 *
 * This class maps to the 'transactions' table in the database.
 * Every deposit, withdrawal, or fund transfer creates one row in this table.
 *
 * HOW TRANSACTIONS WORK:
 * - DEPOSIT:    fromAccount is NULL (money comes from outside the bank),
 *               toAccount   is the account receiving the money.
 * - WITHDRAWAL: fromAccount is the account losing the money,
 *               toAccount   is NULL (money leaves the bank system).
 * - TRANSFER:   fromAccount is the sender's account,
 *               toAccount   is the receiver's account.
 *
 * Database Table Reference:
 * ┌──────────────────┬───────────────┬─────────────────────────────────────────┐
 * │ Column           │ Type          │ Notes                                   │
 * ├──────────────────┼───────────────┼─────────────────────────────────────────┤
 * │ transaction_id   │ INT (PK, AI)  │ Auto-generated by MySQL                 │
 * │ from_account     │ BIGINT (FK)   │ Nullable — NULL for deposits            │
 * │ to_account       │ BIGINT (FK)   │ Nullable — NULL for withdrawals         │
 * │ transaction_type │ VARCHAR(20)   │ 'DEPOSIT', 'WITHDRAWAL', or 'TRANSFER'  │
 * │ amount           │ DECIMAL(15,2) │ The amount transacted                   │
 * │ transaction_time │ TIMESTAMP     │ Auto-set to current time by MySQL       │
 * │ remarks          │ VARCHAR(255)  │ Optional note (e.g. "Self deposit")     │
 * └──────────────────┴───────────────┴─────────────────────────────────────────┘
 */
public class Transaction {

    // --------------------------------------------------
    // Fields — all private (Encapsulation)
    // --------------------------------------------------
    private int    transactionId;   // Primary key, auto-generated by DB
    private long   fromAccount;     // Source account (0 if not applicable — DB stores NULL)
    private long   toAccount;       // Destination account (0 if not applicable)
    private String transactionType; // 'DEPOSIT', 'WITHDRAWAL', or 'TRANSFER'
    private double amount;          // Amount involved in the transaction
    private String transactionTime; // Timestamp string returned from DB
    private String remarks;         // Optional notes about the transaction

    // --------------------------------------------------
    // Constructor 1: No-argument constructor
    // --------------------------------------------------
    // Useful when creating an empty Transaction and setting fields via setters.
    public Transaction() {
    }

    // --------------------------------------------------
    // Constructor 2: For DEPOSIT (no transactionId, no fromAccount)
    // --------------------------------------------------
    // When recording a deposit:
    //   - We don't know transactionId yet (MySQL assigns it).
    //   - fromAccount is irrelevant (money comes from outside the bank).
    //   - toAccount is the account receiving the deposit.
    // 'transactionTime' is also omitted — MySQL auto-sets it via DEFAULT CURRENT_TIMESTAMP.
    public Transaction(long toAccount, String transactionType, double amount, String remarks) {
        this.toAccount       = toAccount;
        this.transactionType = transactionType;
        this.amount          = amount;
        this.remarks         = remarks;
    }

    // --------------------------------------------------
    // Constructor 3: Full constructor (for DB loading)
    // --------------------------------------------------
    // Used when reading a complete transaction row from the database,
    // where all columns including transaction_id and transaction_time are known.
    public Transaction(int transactionId, long fromAccount, long toAccount,
                       String transactionType, double amount,
                       String transactionTime, String remarks) {
        this.transactionId   = transactionId;
        this.fromAccount     = fromAccount;
        this.toAccount       = toAccount;
        this.transactionType = transactionType;
        this.amount          = amount;
        this.transactionTime = transactionTime;
        this.remarks         = remarks;
    }

    // --------------------------------------------------
    // Getters & Setters
    // --------------------------------------------------

    public int getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

    public long getFromAccount() {
        return fromAccount;
    }

    public void setFromAccount(long fromAccount) {
        this.fromAccount = fromAccount;
    }

    public long getToAccount() {
        return toAccount;
    }

    public void setToAccount(long toAccount) {
        this.toAccount = toAccount;
    }

    public String getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getTransactionTime() {
        return transactionTime;
    }

    public void setTransactionTime(String transactionTime) {
        this.transactionTime = transactionTime;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    // --------------------------------------------------
    // toString() — for easy printing / debugging
    // --------------------------------------------------
    @Override
    public String toString() {
        return "Transaction {" +
                " transactionId=" + transactionId +
                ", fromAccount=" + fromAccount +
                ", toAccount=" + toAccount +
                ", transactionType='" + transactionType + '\'' +
                ", amount=" + amount +
                ", transactionTime='" + transactionTime + '\'' +
                ", remarks='" + remarks + '\'' +
                " }";
    }
}
